site_name: Documentation for Linux and BSD on Azure
site_description: Documenation for Linux and BSD on Azure.
repo_url: https://github.com/squillace/staging
theme: readthedocs
pages:
- Azure and Linux VMs: 
    - 'Azure and Linux VMs': 'articles/virtual-machines/virtual-machines-linux-azure-overview.md'
