site_name: Documentation for Linux and BSD on Azure
site_description: Documenation for Linux and BSD on Azure.
repo_url: https://github.com/squillace/staging
theme: bootstrap
pages:
- Home: 'articles/virtual-machines/virtual-machines-linux-azure-overview.md'
- Get Started: 
    - 'Install the Azure CLI': 'articles/xplat-cli-install.md'
    - 'Create a VM for dev/test': 'articles/virtual-machines/virtual-machines-linux-quick-create-cli.md'
    - 'Create SSH keys': 'articles/virtual-machines/virtual-machines-linux-mac-create-ssh-keys.md'
    - 'Create a secured VM from an Azure template': 'articles/virtual-machines/virtual-machines-linux-create-ssh-secured-vm-from-template.md'
    - 'Add a disk': 'articles/virtual-machines/virtual-machines-linux-add-disk.md'
- Tasks:
    - 'Create a VM and custom environment with CLI': 'articles/virtual-machines/virtual-machines-linux-create-cli-complete.md'
    - 'Create a custom VM': 'articles/virtual-machines/virtual-machines-linux-create-upload-generic.md'
    - 'Deploy VMs using Azure templates': 'articles/virtual-machines/virtual-machines-linux-cli-deploy-templates.md'
    - 'Find VM images': 'articles/virtual-machines/virtual-machines-linux-cli-ps-findimage.md'
    - 'Capture VM images': 'articles/virtual-machines/virtual-machines-linux-capture-image.md'    
    - 'Deploy common app frameworks using Azure templates': 'articles/virtual-machines/virtual-machines-linux-app-frameworks.md'
    - 'Disable SSH passwords on your VM': 'articles/virtual-machines/virtual-machines-linux-mac-disable-ssh-password-usage.md' 
- Tutorials:
    - 'Deploy Jupyter notebook': 'articles/virtual-machines/virtual-machines-linux-jupyter-notebook.md'
    - 'Deploy a LAMP Stack': 'articles/virtual-machines/virtual-machines-linux-create-lamp-stack.md'
    - 'Deploy a 3-node Deis cluster': 'articles/virtual-machines/virtual-machines-linux-deis-cluster.md'
    - 'Deploy a Microsoft HPC cluster': 'articles/virtual-machines/virtual-machines-linux-hpcpack-cluster-options.md'
    - 'Deploy MySQL': 'articles/virtual-machines/virtual-machines-linux-mysql-install.md'
    - 'Deploy PostgreSQL': 'articles/virtual-machines/virtual-machines-linux-postgresql-install.md'
    - 'Deploy Django Hello World web app': 'articles/virtual-machines/virtual-machines-linux-python-django-web-app.md'
    - 'Testing SAP NetWeaver on SUSE Linux': 'articles/virtual-machines/virtual-machines-linux-sap-on-suse-quickstart.md'
- Azure VM:
    - Concepts:
        - 'Subscription and Service Limits, Quotas, and Constraints': 'articles/azure-subscription-service-limits.md'
        - 'Azure Linux Agent User Guide': 'articles/virtual-machines/virtual-machines-linux-agent-user-guide.md'
        - 'User Names for Linux VMs': 'articles/virtual-machines/virtual-machines-linux-usernames.md'
        - 'Root privileges on Azure': 'articles/virtual-machines/virtual-machines-linux-use-root-privileges.md'
        - 'Azure-Endorsed Distributions': 'articles/virtual-machines/virtual-machines-linux-endorsed-distros.md'
        - 'VM Sizes': 'articles/virtual-machines/virtual-machines-linux-sizes.md'
        - 'Tag a VM': 'articles/virtual-machines/virtual-machines-linux-tag.md'
        - 'Autoscale VMs with Scale Sets': 'articles/virtual-machines/virtual-machines-linux-cli-vmss-create.md'
        - 'Azure Resource Groups': 'articles/resource-group-overview.md'
    - Create and Upload VHDs for Azure:
        - 'Prepare a Debian VHD': 'articles/virtual-machines/virtual-machines-linux-debian-create-upload-vhd.md'
        - 'Prepare an Ubuntu VHD': 'articles/virtual-machines/virtual-machines-linux-create-upload-ubuntu.md'
        - 'Prepare a Red Hat-based VHD': 'articles/virtual-machines/virtual-machines-linux-redhat-create-upload-vhd.md'
        - 'Prepare a SLES or openSUSE VHD': 'articles/virtual-machines/virtual-machines-linux-suse-create-upload-vhd.md'
        - 'Prepare a CentOS-based VHD': 'articles/virtual-machines/virtual-machines-linux-create-upload-centos.md'
        - 'Prepare an Oracle Linux VHD': 'articles/virtual-machines/virtual-machines-linux-oracle-create-upload-vhd.md'
        - 'Prepare another Linux VHD': 'articles/virtual-machines/virtual-machines-linux-create-upload-generic.md'
    - Plan and Manage: 
        - 'Azure infrastructure implementation guidelines': 'articles/virtual-machines/virtual-machines-linux-infrastructure-service-guidelines.md'
        - 'Plan availability of Linux VMs': 'articles/virtual-machines/virtual-machines-linux-manage-availability.md'
        - 'Planned maintenance for Azure VMs': 'articles/virtual-machines/virtual-machines-linux-planned-maintenance.md'
        - 'Schedule Planned Maintenance on VMs': 'articles/virtual-machines/virtual-machines-linux-planned-maintenance-schedule.md'
        - 'Enable or Disable VM monitoring': 'articles/virtual-machines/virtual-machines-linux-vm-monitoring.md'
        - 'Deploy update infrastructure for Red Hat Enterprise Linux': 'articles/virtual-machines/virtual-machines-linux-update-infrastructure-redhat.md'
        - 'Optimize your Linux VM': 'articles/virtual-machines/virtual-machines-linux-optimization.md'
    - VM Extensions: 
        - 'Linux VM extensions': 'articles/virtual-machines/virtual-machines-linux-extensions-features.md'
        - 'Authoring Azure templates with Linux VM extensions': 'articles/virtual-machines/virtual-machines-linux-extensions-authoring-templates.md'
        - 'Linux VM extension samples': 'articles/virtual-machines/virtual-machines-linux-extensions-configuration-samples.md'
        - 'Use the CustomScript extension for Linux VMs': 'articles/virtual-machines/virtual-machines-linux-extensions-customscript.md'
        - 'Use the Docker VM extension': 'articles/virtual-machines/virtual-machines-linux-dockerextension.md'
        - 'AzureLogCollector VM extension': 'articles/virtual-machines/virtual-machines-linux-log-collector-extension.md'
- Networking:
    - 'Azure Networking Overview': 'articles/virtual-network/virtual-networks-overview.md'
- Storage:
    - 'Azure Storage Overview': 'articles/storage/storage-azure-cli.md'
- Troubleshooting and Support:
    - 'Troubleshoot SSH connections': 'articles/virtual-machines/virtual-machines-linux-troubleshoot-ssh-connection.md'
    - 'Troubleshoot application access': 'articles/virtual-machines/virtual-machines-linux-troubleshoot-app-connection.md'
    - 'Troubleshoot VM extension failures': 'articles/virtual-machines/virtual-machines-linux-extensions-troubleshoot.md'
    - 'Troubleshoot allocation failures': 'articles/virtual-machines/virtual-machines-linux-allocation-failure.md'
    - 'Redeploy VM to a new Azure node': 'articles/virtual-machines/virtual-machines-linux-redeploy-to-new-node.md'

