site_name: Documentation for Linux and BSD on Azure
site_description: Documenation for Linux and BSD on Azure.
repo_url: https://github.com/squillace/staging
theme: readthedocs
pages:
- Azure and Linux VMs: 
    - 'Azure for Linux Workloads': 'articles/virtual-machines/virtual-machines-linux-azure-overview.md'
- Get Started: 
    - 'Install the Azure CLI': 'articles/xplat-cli-install.md'
    - 'Create a VM for dev/test': 'articles/virtual-machines/virtual-machines-linux-quick-create-cli.md'
    - 'Create SSH keys': 'articles/virtual-machines/virtual-machines-linux-mac-create-ssh-keys.md'
    - 'Create a secured VM from an Azure template': 'articles/virtual-machines/virtual-machines-linux-create-ssh-secured-vm-from-template.md'
    - 'Add a disk': 'articles/virtual-machines/virtual-machines-linux-add-disk.md'
- Advanced Tasks:
    - 'Create a VM and custom environment with CLI': 'articles/virtual-machines/virtual-machines-linux-create-cli-complete.md'
    - 'Create and upload a custom VM': 'articles/virtual-machines/virtual-machines-linux-create-upload-generic.md'
    - 'Deploy popular application frameworks by using Azure Resource Manager templates': 'articles/virtual-machines/virtual-machines-linux-app-frameworks.md'
    - 'Deploy VMs using Azure templates': 'article/virtual-machines/virtual-machines-linux-cli-deploy-templates.md'
    - 'Capture VM images in Azure': 'article/virtual-machines/virtual-machines-linux-capture-image.md'    
    - 'Find VM images to use in Azure': 'article/virtual-machines/virtual-machines-linux-cli-ps-findimage.md'
    - 'Disable SSH passwords on your Linux VM': 'articles/virtual-machines/virtual-machines-linux-mac-disable-ssh-password-usage.md' 
- Tutorials:
    - 'Deploy Jupyter notebook': 'articles/virtual-machines/virtual-machines-linux-jupyter-notebook.md'
    - 'Deploy a LAMP Stack': 'articles/virtual-machines/virtual-machines-linux-create-lamp-stack.md'
    - 'Deploy a 3-node Deis cluster': 'articles/virtual-machines/virtual-machines-linux-deis-cluster.md'
    - 'Deploy and manage an HPC cluster with Microsoft HPC Pack': 'articles/virtual-machines/virtual-machines-linux-hpcpack-cluster-options.md'
    - 'Deploy MySQL VM': 'articles/virtual-machines/virtual-machines-linux-mysql-install.md'
    - 'Deploy and configure PostgreSQL on a Linux VM': 'artiles/virtual-machines/virtual-machines-linux-postgresql-install.md'
    - 'Deploy Django Hello World web app': 'articles/virtual-machines/virtual-machines-linux-python-django-web-app.md'
    - 'Testing SAP NetWeaver on SUSE Linux': 'articles/virtual-machines/virtual-machines-linux-sap-on-suse-quickstart.md'
- VMs:
    - Concepts:
        - 'Microsoft Azure Subscription and Service Limits, Quotas, and Constraints': 'articles/azure-subscription-service-limits.md'
        - 'Azure Linux Agent User Guide': 'articles/virtual-machines/virtual-machines-linux-agent-user-guide.md'
        - 'Selecting User Names for Linux on Azure': 'azure/virtual-machines/virtual-machines-linux-usernames.md'
        - 'Use root privileges on Azure VMs': 'articles/virtual-machines/virtual-machines-linux-use-root-privileges.md'
        - 'Azure-Endorsed Distributions': 'articles/virtual-machines/virtual-machines-linux-endorsed-distros.md'
        - 'VM Sizes': 'articles/virtual-machines/virtual-machines-linux-sizes.md'
        - 'Tag a VM': 'articles/virtual-machines/virtual-machines-linux-tag.md'
        - 'Autoscale VMs with Scale Sets': 'articles/virtual-machines/virtual-machines-linux-cli-vmss-create.md'
        - 'Azure Resource Groups': 'articles/articles/resource-group-overview.md'
    - Create and Upload VHDs for Azure:
        - 'Prepare a Debian VHD': 'articles/virtual-machines/virtual-machines-linux-debian-create-upload-vhd.md'
        - 'Prepare an Ubuntu VHD': 'articles/virtual-machines/virtual-machines-linux-create-upload-ubuntu.md'
        - 'Prepare a Red Hat-based VHD': 'articles/virtual-machines/virtual-machines-linux-redhat-create-upload-vhd.md'
        - 'Prepare a SLES or openSUSE VHD': 'articles/virtual-machines/virtual-machines-linux-suse-create-upload-vhd.md'
        - 'Prepare a CentOS-based VHD': 'articles/virtual-machines/virtual-machines-linux-create-upload-centos.md'
        - 'Prepare an Oracle Linux VHD': 'articles/virtual-machines/virtual-machines-linux-oracle-create-upload-vhd.md'
        - 'Information for Non-Endorsed Distributions': 'articles/virtual-machines/virtual-machines-linux-create-upload-generic.md'
    - Plan: 
        - 'Azure infrastructure services implementation guidelines': 'articles/virtual-machines/virtual-machines-linux-infrastructure-service-guidelines.md'
        - 'Plan availability of Linux virtual machines': 'articles/virtual-machines/virtual-machines-linux-manage-availability.md'
    - Manage:
        - 'Planned maintenance for Azure VMs': 'articles/virtual-machines/virtual-machines-linux-planned-maintenance.md'
        - 'Schedule Planned Maintenance on VMs': 'articles/virtual-machines/virtual-machines-linux-planned-maintenance-schedule.md'
        - 'Enable or Disable VM monitoring': 'articles/virtual-machines/virtual-machines-linux-vm-monitoring.md'
        - 'Deploy update infrastructure for Red Hat Enterprise Linux': 'articles/virtual-machines/virtual-machines-linux-update-infrastructure-redhat.md'
        - 'Optimize your Linux VM': 'articles/virtual-machines/virtual-machines-linux-optimization.md'
    - VM Extensions: 'articles/virtual-machines/virtual-machines-linux-extensions-features.md'
        - 'Authoring Azure templates with Linux VM extensions': 'articles/virtual-machines/virtual-machines-linux-extensions-authoring-templates.md'
        - 'Linux VM extension samples': 'articles/virtual-machines/virtual-machines-linux-extensions-configuration-samples.md'
        - 'Use the CustomScript extension for Linux VMs': 'articles/virtual-machines/virtual-machines-linux-extensions-customscript.md'
        - 'Use the Docker VM extension': 'articles/virtual-machines/virtual-machines-linux-dockerextension.md'
        - 'AzureLogCollector VM extension': 'articles/virtual-machines/virtual-machines-linux-log-collector-extension.md'
- Azure Container Service and Linux Containers
    - 'Virtual Machines and Containers in Azure': 'articles/virtual-machines/virtual-machines-linux-containers.md'
    - 'Azure Container Service': 'articles/container-service/container-service-intro.md'
    - 'Deploy an Azure Container Service cluster': 'articles/container-service/container-service-deployment.md'
    - 'Connect to an Azure Container Service cluster': 'articles/container-service/container-service-connect.md'
    - 'Container management through the web UI': 'articles/container-service/container-service-mesos-marathon-ui.md'
    - 'Container management with the REST API': 'articles/container-service/container-service-mesos-marathon-rest.md'
    - 'Docker swarm on Azure Container Service': 'articles/container-service/container-service-docker-swarm.md'
    
    
- Networking: 
    - 'Design Customization': 'customize/design.md'
 
- Storage:
    - 'SCIM UMA How-to': 'integrate/scimuma-howto.md'

- Troubleshooting and Support:
    - 'Troubleshoot SSH connections': 'article/virtual-machines/virtual-machines-linux-troubleshoot-ssh-connection.md'
	- 'Troubleshoot application access': 'article/virtual-machines/virtual-machines-linux-troubleshoot-app-connection.md'
	- 'Troubleshoot VM extension failures': 'article/virtual-machines/virtual-machines-linux-extensions-troubleshoot.md'
	- 'Troubleshoot allocation failures': 'article/virtual-machines/virtual-machines-linux-allocation-failure.md'
    - 'Redeploy VM to a new Azure node': 'articles/virtual-machines/virtual-machines-linux-redeploy-to-new-node.md'

- Reference:
    - 'Tuning LDAP, Tomcat': 'fine-tuning/index.md'
